services:
  spa:
    build:
      context: ../spa
      dockerfile: ../docker/spa.Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ../api
      dockerfile: ../docker/api.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mongo:8.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1})"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
